# !!! This package (xorg-libpthread-stubs) has been deprecated in favor of
# `pthread-stubs` for compatibility with Anaconda `defaults` !!!!

{% set xorg_name = "libpthread-stubs" %}
{% set xorg_category = "xcb" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "0.4" %}
{% set sha256 = "e4d05911a3165d3b18321cc067fdd2f023f06436e391c6a28dff618a78d2e733" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

# NOTE: no Visual Studio dependent features, since this package does not build
# or install any binary code on Windows. It needs m2w64-toolchain for the
# configure script to run, but msys2 provides sufficient pthreads bits for
# downstream packages.

build:
  skip: true # !!!!!!!!
  number: 1000
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-toolchain  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - toolchain
    - xorg-util-macros

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Multithreading stubs for X.org client libraries.'

extra:
  recipe-maintainers:
    - pkgw
