appveyor:
  secure: {BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sgcAXqdq+CjX+I+dVYdBEL8kX01aj8NLtz5O4dG4SRc86c8tZuEEy2793oXVy4U2Lx4NstkAg6K7ZMIgcmHSXJxzkxPOzROIxWlp3eUpa3R8VfvjiMx45lob7f86Xnu0mbpOnWVRF6F2XR5iXD1Q4yNVsK11T4uSedo50ap0uYqByAHttd6/Q7y8Lf5c8ob38mYRKVI4WQ7e7YTrKF0tPu4xaN8W8YHVSUCbGrwKy6KHvb3hKAGKCxtmO/lyY5KQSq94ksW2Fb03DRB+OwOYQh6AndFBZEvix05MGljZ+VWk9gEpevg7REA2NuA74VRzVthymR58qjE/fcMdKQl/wKZKx/DQWbtYNqo72FyXHnQXG4pCXre5qUFhZG+ELfnlH/F3PijTuXW70Z/mAVZRD9/889/TShRo8Pw27IYaWI+AQ3655bzI1OnqX4riO0xV71UcF2hZUbrB+TPvy6hroO0zLlppK0JZrCZjwMw3Yq6KxxNPrMZ/VvfEK6MxrJErPNannFfQOhgFVn1CPDjmukon+ha+jhEB8k9c8E3U0jd+8jm6QFCRWiLS67IPXY8MkQm5zCwpOz9tidnhsM0Lb0QLKcnzf1fFJ1cCsczMHFsH3bOnv7u6doGnCMKi4L2Y3Yf45xrQU4EF3Z0mxA9dFrtb3BcoAnPxZQMr49gjmxc=}
